name: Deploy Notebook

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nbconvert
        run: |
          pip install nbconvert

      - name: Convert notebook to HTML
        run: |
          jupyter nbconvert hr_analytics.ipynb --to html --output index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: index.html # <â€” specify the file, not "."

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
